CREATE TABLE IF NOT EXISTS cdt.{{ table_name }} (
  market_segment                       VARCHAR    COMMENT 'Market filter segments (All, Launch/Express...)',
  active_customer_count                BIGINT     COMMENT 'Distinct active customer accounts',
  active_deployment_count_all          BIGINT     COMMENT 'Active deployments - all types',
  active_deployment_count_initial      BIGINT     COMMENT 'Active deployments - Initial',
  active_deployment_count_phase_x      BIGINT     COMMENT 'Active deployments - Subsequent',
  activity_initial_tool_usage          BIGINT     COMMENT 'Implementer activity - Initial',
  activity_initial_migrated            BIGINT     COMMENT 'Implementer migrated activity - Initial',
  activity_phase_x_tool_usage          BIGINT     COMMENT 'Implementer activity - Subsequent',
  activity_phase_x_migrated            BIGINT     COMMENT 'Implementer migrated activity - Subsequent',
  activity_customer_all                BIGINT     COMMENT 'Customer activity - all tools',
  activity_customer_all_migrated       BIGINT     COMMENT 'Customer migrated activity - all tools',
  activity_initial_ct_tc_tool_usage    BIGINT     COMMENT 'CT_TC_AS group - Initial tool usage',
  activity_initial_ct_tc_migrated      BIGINT     COMMENT 'CT_TC_AS group - Initial migrated',
  activity_phase_x_ct_tc_tool_usage    BIGINT     COMMENT 'CT_TC_AS group - Subsequent tool usage',
  activity_phase_x_ct_tc_migrated      BIGINT     COMMENT 'CT_TC_AS group - Subsequent migrated',
  activity_customer_ct_tc              BIGINT     COMMENT 'CT_TC_AS group - Customer activity',
  activity_customer_ct_tc_migrated     BIGINT     COMMENT 'CT_TC_AS group - Customer migrated',
  activity_initial_fr_mr_migrated      BIGINT     COMMENT 'FR_MR group - Initial migrated',
  activity_phase_x_fr_mr_migrated      BIGINT     COMMENT 'FR_MR group - Subsequent migrated',
  activity_initial_ct_tool_usage       BIGINT     COMMENT 'Change Tracker - Initial tool usage',
  activity_initial_ct_migrated         BIGINT     COMMENT 'Change Tracker - Initial migrated',
  activity_phase_x_ct_tool_usage       BIGINT     COMMENT 'Change Tracker - Subsequent tool usage',
  activity_phase_x_ct_migrated         BIGINT     COMMENT 'Change Tracker - Subsequent migrated',
  activity_customer_ct                 BIGINT     COMMENT 'Change Tracker - Customer activity',
  activity_customer_ct_migrated        BIGINT     COMMENT 'Change Tracker - Customer migrated',
  activity_initial_tc_tool_usage       BIGINT     COMMENT 'Tenant Compare - Initial tool usage',
  activity_initial_tc_migrated         BIGINT     COMMENT 'Tenant Compare - Initial migrated',
  activity_phase_x_tc_tool_usage       BIGINT     COMMENT 'Tenant Compare - Subsequent tool usage',
  activity_phase_x_tc_migrated         BIGINT     COMMENT 'Tenant Compare - Subsequent migrated',
  activity_customer_tc                 BIGINT     COMMENT 'Tenant Compare - Customer activity',
  activity_customer_tc_migrated        BIGINT     COMMENT 'Tenant Compare - Customer migrated',
  activity_initial_as_tool_usage       BIGINT     COMMENT 'Adhoc Scope - Initial tool usage',
  activity_initial_as_migrated         BIGINT     COMMENT 'Adhoc Scope - Initial migrated',
  activity_phase_x_as_tool_usage       BIGINT     COMMENT 'Adhoc Scope - Subsequent tool usage',
  activity_phase_x_as_migrated         BIGINT     COMMENT 'Adhoc Scope - Subsequent migrated',
  activity_customer_as                 BIGINT     COMMENT 'Adhoc Scope - Customer activity',
  activity_customer_as_migrated        BIGINT     COMMENT 'Adhoc Scope - Customer migrated',
  activity_initial_fr_migrated         BIGINT     COMMENT 'Foundation Recipe - Initial migrated',
  activity_phase_x_fr_migrated         BIGINT     COMMENT 'Foundation Recipe - Subsequent migrated',
  activity_initial_mr_migrated         BIGINT     COMMENT 'Migration Recipe - Initial migrated',
  activity_phase_x_mr_migrated         BIGINT     COMMENT 'Migration Recipe - Subsequent migrated',
  comments                             VARCHAR    COMMENT 'Data quality note',
  window_start                         DATE       COMMENT 'Start of 6-month rolling window',
  computed_at                          TIMESTAMP  COMMENT 'When the DAG computed this row',
  snapshot_date                        DATE       COMMENT 'Partition column - the date this snapshot represents'
)
WITH (
  format = 'PARQUET',
  partitioned_by = ARRAY['snapshot_date']
)
