INSERT INTO cdt.{{ main_table_name }}   -- main_table_name to be set in the Python Script
SELECT
    implementation_type_name,
    module,
    tools,
    environment,
    cast(composite_type AS BOOLEAN),
    cast("count" AS BIGINT),
    cast(avg_transformation_time AS REAL),
    cast(max_trans_time AS BIGINT),
    cast("90_perc_trans_time" AS REAL),
    cast("95_perc_trans_time" AS REAL),
    cast(avg_ws_time AS REAL),
    cast(max_ws_time AS BIGINT),
    cast("90_perc_ws_time" AS REAL),
    cast("95_perc_ws_time" AS REAL),
    cast(avg_total_time AS REAL),
    cast(max_total_time AS BIGINT),
    cast("90_perc_total_time" AS REAL),
    cast("95_perc_total_time" AS REAL),
    cast(sum_instance_count AS BIGINT),
    cast(max_instance_count AS BIGINT),
    cast("90_perc_instance_count" AS REAL),
    cast("95_perc_instance_count" AS REAL),
    cast(mean_trans_time_per_instance AS REAL),
    cast(std_trans_time_per_instance AS REAL),
    cast(mean_ws_time_per_instance AS REAL),
    cast(std_ws_time_per_instance AS REAL),
    cast(mean_tot_time_per_instance AS REAL),
    cast(std_tot_time_per_instance AS REAL),
    cast(month AS DATE)
FROM cdt.{{ temp_table_name }}    -- temp_table_name to be set in the Python Script